name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - uses: dylan-lang/install-dylan-tool@v2

      - name: Build tests
        run: | 
          dylan update
          dylan build v3d-test

      - name: Run tests
        run: _build/bin/v3d-test

      - name: Install sphinx
        run: |
          sudo apt-get install -y python3-sphinx python3-sphinxcontrib.plantuml

      - name: Build docs
        run: |
          cd documentation
          make html
          cd ..

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/build/html
          target-folder: docs/v3d
